title: ComfyUI
name: comfyui
use_python: true
python_version: "3.13"
expose: true
port: 7005

prepare_repo: |-

  TARGET_REPO_URL="https://github.com/comfyanonymous/ComfyUI.git" \
  TARGET_REPO_DIR=$REPO_DIR \
  UPDATE_REPO=${{ name|upper }}_UPDATE_REPO \
  UPDATE_REPO_COMMIT=${{ name|upper }}_UPDATE_REPO_COMMIT \
  prepare_repo 

prepare_env: |-
  python $WORKING_DIR/utils/create_symlinks.py $current_dir/folder_mapping.json $MODEL_DIR $REPO_DIR/models

  cd $REPO_DIR
  $UV_INSTALL_DIR/uv pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu130
  $UV_INSTALL_DIR/uv pip install -r requirements.txt

  cd "$REPO_DIR/custom_nodes"
  if [[ ! -d "comfyui-manager" ]]; then
    git clone https://github.com/ltdrdata/ComfyUI-Manager comfyui-manager
  fi

download_model: |-
  bash $WORKING_DIR/utils/sd_model_download/main.sh

action_before_start: ""

start: |-
  cd "$REPO_DIR"
  mkdir -p $ROOT_REPO_DIR/settings/{{ name }}
  PYTHONUNBUFFERED=1 service_loop "python main.py --dont-print-server --port ${{ name|upper }}_PORT --user-directory $ROOT_REPO_DIR/settings/{{ name }} ${EXTRA_{{ name|upper }}_ARGS}" > $LOG_DIR/{{ name }}.log 2>&1 &
  echo $! > /tmp/{{ name }}.pid

export_required_env: ""
setup_env: |-
  export MODEL_DIR="$DATA_DIR/models"
  export REPO_DIR="$ROOT_REPO_DIR/ComfyUI"

  export {{ name|upper }}_PORT="{{ port }}"
  export EXPOSE_PORTS="$EXPOSE_PORTS:${{ name|upper }}_PORT"
  export PORT_MAPPING="$PORT_MAPPING:{{ name }}"
  export HUGGINGFACE_TOKEN=$HF_TOKEN

extra_files:
  folder_mapping.json: |-
    {
      "audio_encoders": "AudioEncoder",
      "checkpoints": "Checkpoints",
      "clip": "Clip",
      "clip_vision": "ClipVision",
      "controlnet": "ControlNet",
      "diffusers": "Diffusers",
      "diffusion_models": "DiffusersModels",
      "embeddings": "TextualInversion",
      "gligen": "Gligen",
      "hypernetworks": "Hypernetworks",
      "latent_upscale_models": "LatentUpscaleModels",
      "loras": "Loras",
      "model_patches": "ModelPatches",
      "photomaker": "Photomaker",
      "style_models": "StyleModels",
      "text_encoders": "TextEncoder",
      "unet": "Unet",
      "upscale_models": "UpscaleModels",
      "vae": "VAE",
      "vae_approx": "ApproxVAE",
      "loras": "Loras",
      "upscale_models": "UpscaleModels"
    }

  