title: Stable Diffusion InvokeAI
name: invokeai
use_python: true
python_version: "3.11"
expose: true
port: 7006

prepare_repo: |-
  mkdir -p $DATA_DIR/invokeai_models
  mkdir -p $INVOKEAI_ROOT/models

  symlinks=(
    "$INVOKEAI_ROOT/outputs:$IMAGE_OUTPUTS_DIR/invokeai"
    "$DATA_DIR/invokeai_models:$INVOKEAI_ROOT/models"
  )
  prepare_link "${symlinks[@]}"

prepare_env: |-
  if [[ "$INVOKEAI_INSTALL_PYPATCHMATCH" ]]; then
    echo "Installing pypatchmatch"
    apt-get install build-essential -y > /dev/null
    apt-get install python3-opencv libopencv-dev -y > /dev/null
    $UV_INSTALL_DIR/uv pip install pypatchmatch
  fi

  $UV_INSTALL_DIR/uv pip install invokeai --index https://download.pytorch.org/whl/cu124

download_model: |-
  bash $current_dir/../utils/sd_model_download/main.sh

action_before_start: ""

start: |-
  cd "$REPO_DIR"
  mkdir -p $ROOT_REPO_DIR/settings/invokeai
  PYTHONUNBUFFERED=1 service_loop "invokeai-web --config $current_dir/config.yaml \
  ${EXTRA_{{ name|upper }}_ARGS}" > $LOG_DIR/{{ name }}.log 2>&1 &
  echo $! > /tmp/{{ name }}.pid

export_required_env: ""
setup_env: |-

  export MODEL_DIR=${{ '{' ~ name|upper }}_MODEL_DIR:-"$DATA_DIR/stable-diffusion-models"}
  export REPO_DIR=${{ '{' ~ name|upper }}_REPO_DIR:-"$ROOT_REPO_DIR/stable-diffusion-invokeai"}
  export INVOKEAI_ROOT=$ROOT_REPO_DIR/settings/invokeai
  export HUGGING_FACE_HUB_TOKEN=$HF_TOKEN

  export {{ name|upper }}_PORT=${{ '{' ~ name|upper }}_PORT:-"7006"}
  export EXPOSE_PORTS="$EXPOSE_PORTS:${{ name|upper }}_PORT"
  export PORT_MAPPING="$PORT_MAPPING:{{ name }}"
  export HUGGINGFACE_TOKEN=$HF_TOKEN

extra_files:
  config.yaml: |-
    # Internal metadata - do not edit:
    schema_version: 4.0.2

    # Put user settings here - see https://invoke-ai.github.io/InvokeAI/configuration/:
    enable_partial_loading: true
    pytorch_cuda_alloc_conf: "backend:cudaMallocAsync"
  