title: SwarmUI
name: swarmui
use_python: true
python_version: "3.11"
expose: true
port: 7016

prepare_repo: |-

  TARGET_REPO_URL="https://github.com/mcmonkeyprojects/SwarmUI.git" \
  TARGET_REPO_DIR=$REPO_DIR \
  TARGET_REPO_BRANCH="master" \
  UPDATE_REPO=${{ name|upper }}_UPDATE_REPO \
  UPDATE_REPO_COMMIT=${{ name|upper }}_UPDATE_REPO_COMMIT \
  prepare_repo 


prepare_env: |-
  python $WORKING_DIR/utils/create_symlinks.py $current_dir/folder_mapping.json $MODEL_DIR $REPO_DIR/models

  apt-get update -qq
  apt-get install -qq -y dotnet-sdk-8.0

  $UV_INSTALL_DIR/uv pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu126

download_model: |-
  bash $WORKING_DIR/utils/sd_model_download/main.sh

action_before_start: ""

start: |-
  cd $REPO_DIR
  mkdir $ROOT_REPO_DIR/settings/{{ name }}
  service_loop "bash launch-linux.sh --data_dir $ROOT_REPO_DIR/settings/{{ name }} --port {{ port }} --launch_mode none ${EXTRA_{{ name|upper }}_ARGS}" > $LOG_DIR/{{ name }}.log 2>&1 &
  echo $! > /tmp/{{ name }}.pid

export_required_env: ""
setup_env: |-
  export MODEL_DIR=${{ '{' ~ name|upper }}_MODEL_DIR:-"$DATA_DIR/stable-diffusion-models"}
  export REPO_DIR=${{ '{' ~ name|upper }}_REPO_DIR:-"$ROOT_REPO_DIR/StableSwarmUI"}

  export {{ name|upper }}_PORT=${{ '{' ~ name|upper }}_PORT:-"{{ port }}"}
  export EXPOSE_PORTS="$EXPOSE_PORTS:${{ name|upper }}_PORT"
  export PORT_MAPPING="$PORT_MAPPING:{{ name }}"
  
extra_files:
  folder_mapping.json: |-
    {
      "Stable-Diffusion": "StableDiffusion",
      "VAE": "VAE",
      "Lora": [
        "Lora",
        "LyCORIS"
      ],
      "upscale_models": [
        "ESRGAN",
        "RealESRGAN",
        "SwinIR"
      ],
      "Embeddings": "TextualInversion",
      "controlnet": [
        "ControlNet",
        "T2IAdapter"
      ],
      "clip": "TextEncoder",
      "diffusion_models": "Unet"
    }